name: Build macOS App

on:
  push:
    branches:
      - main  # Trigger the build on the main branch (adjust if you're using a different branch)

jobs:
  build:
    runs-on: macos-latest  # Use macOS as the environment for the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.x'  # Adjust to the required Python version

      - name: Install dependencies
        run: |
          pip install pyinstaller  # Install PyInstaller

      - name: Build the macOS app
        run: |
          pyinstaller --onefile --windowed --distpath=dist --workpath=build dynamixelControl.py  # Replace with your script name

      - name: Upload built .app as artifact
        uses: actions/upload-artifact@v3  # Latest version of upload-artifact
        with:
          name: MyApp  # Artifact name
          path: dist/dynamixelControl  # Path to the generated .app (adjust as necessary)
